---
abstract: 'Organize your Mouse types in libraries'
author:
  - 'Kazuhiro Osawa <yappo <at> shibuya <döt> pl>'
build_requires:
  Scalar::Util: 0
  Test::Exception: 0
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.750'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: MouseX-Types
no_index:
  directory:
    - inc
    - t
requires:
  Mouse: 0.15
version: 0.01
