---
abstract: 'Organize your Mouse types in libraries'
author:
  - 'Kazuhiro Osawa <yappo <at> shibuya <döt> pl>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Scalar::Util: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MouseX-Types
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Mouse: 0.41
  perl: 5.6.2
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/yappo/p5-mousex-types.git
version: 0.03
